replicaCount: 3

image:
  repository: rsilveira/hearst_tha
  pullPolicy: Never
  tag: "1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    memory: 30Mi
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 60
  